### ISSUE TITLE
[Enhancement] Alert when showing error if theres no history 

### ISSUE THREAD

**Issue by yolk23** [DhanushNehru/calculator#142]
**Description:**
For better UX we can change this into a toast instead of an alert
![image](https://github.com/user-attachments/assets/5642da1d-cc1a-4a9a-b9fa-636dd6cf8498)

**Comment by MohammedJunaid02** [comment]
Hi @DhanushNehru , shall I start work on this.?
Here is the UI for the Toast Message instead of the old boring alert box


https://github.com/user-attachments/assets/9dca7fd2-7ed3-48ed-b152-00f8ec92a805

If you are ok with this UI I can start integrating this on the project and raise a pull request for the same.
Thank You

**Comment by DhanushNehru** [comment]
Hi @MohammedJunaid02 @yolk23 , thanks for your inputs ,

From looking at the two, It seems @MohammedJunaid02 UX is better, so assigning to him

**Comment by MohammedJunaid02** [comment]
Hey @DhanushNehru ,

I have raised the PR for this issue, Please review it once and merge it.

PR Link : https://github.com/DhanushNehru/calculator/pull/152/

FYI, I have done some unit testing as well

Thank You

**Comment by MohammedJunaid02** [comment]
Also @DhanushNehru ,
This will be the final look for the Toast Message, Please have a look

Uploading Calc Issue Delete (1).mp4…

**Comment by MohammedJunaid02** [comment]
Gentle Reminder @DhanushNehru Review and merge this PR so that i can take the latest changes from the main branch and proceed with other issues for Toast Messages...!

Also @DhanushNehru , please note that I will fix all the alert to change it to a Toast Message, so please don't assign this because there will be no uniformity in the UI, someone maybe making another UI which will contradict with my UI for Toast Messages and hence there will be a bad User Exprerience to the end-user.!

Keeping this thing in mind, please do not try to assign issue or merge the PR related to the changes. Hope you understand.

Thank You.!

**Comment by MohammedJunaid02** [comment]
@DhanushNehru 
Can you please add Hacktoberfest label to this issue, so that Hacktoberfest Maintainers can consider this under that
